services:
  backend:
    build: ./backend
    container_name: cha-backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGO_URI: mongodb://mongodb:27017/cancer_helper_ai      
      SECRET_TOKEN_KEY: superUltraMegaSecretKey123
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: cha-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  mongodb:
    image: mongo:6.0
    container_name: cha-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
